import initScrollSuave from "./modules/scroll-suave.js";
import initAnimationScroll from "./modules/anima-scroll.js";
import initTabNav from "./modules/nav-tabs.js";
import initAccordion from "./modules/nav-accordion.js";
import initmodal from "./modules/modal-login.js";
import InitTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initAnimaNumero from "./modules/anima-numeros.js";
import initFuncionamento from "./modules/funcionamento.js";
import initFetchBitcoin from "./modules/fetchBitcoins.js";

initScrollSuave();
initAnimationScroll();
initAccordion();
initTabNav();
initmodal();
InitTooltip();
initDropdownMenu();
initMenuMobile();
initAnimaNumero();
initFuncionamento();
initFetchBitcoin();
